"""add excel import tracking

Revision ID: 112374d61292
Revises: 239701e4909d
Create Date: 2026-09-13 19:33:18.833770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '112374d61292'
down_revision: Union[str, None] = '239701e4909d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('days_created', sa.Integer(), nullable=False),
    sa.Column('days_updated', sa.Integer(), nullable=False),
    sa.Column('days_unchanged', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_file_hash'), 'import_batches', ['file_hash'], unique=False)
    op.create_table('imported_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imported_days_date'), 'imported_days', ['date'], unique=True)
    op.add_column('car_entries', sa.Column('imported_day_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_car_entries_imported_day_id'), 'car_entries', ['imported_day_id'], unique=False)
    op.create_foreign_key(None, 'car_entries', 'imported_days', ['imported_day_id'], ['id'], ondelete='CASCADE')
    op.add_column('day_closings', sa.Column('imported_day_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_day_closings_imported_day_id'), 'day_closings', ['imported_day_id'], unique=False)
    op.create_foreign_key(None, 'day_closings', 'imported_days', ['imported_day_id'], ['id'], ondelete='CASCADE')
    op.add_column('expenses', sa.Column('imported_day_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_expenses_imported_day_id'), 'expenses', ['imported_day_id'], unique=False)
    op.create_foreign_key(None, 'expenses', 'imported_days', ['imported_day_id'], ['id'], ondelete='CASCADE')
    op.add_column('puc_entries', sa.Column('imported_day_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_puc_entries_imported_day_id'), 'puc_entries', ['imported_day_id'], unique=False)
    op.create_foreign_key(None, 'puc_entries', 'imported_days', ['imported_day_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'puc_entries', type_='foreignkey')
    op.drop_index(op.f('ix_puc_entries_imported_day_id'), table_name='puc_entries')
    op.drop_column('puc_entries', 'imported_day_id')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_imported_day_id'), table_name='expenses')
    op.drop_column('expenses', 'imported_day_id')
    op.drop_constraint(None, 'day_closings', type_='foreignkey')
    op.drop_index(op.f('ix_day_closings_imported_day_id'), table_name='day_closings')
    op.drop_column('day_closings', 'imported_day_id')
    op.drop_constraint(None, 'car_entries', type_='foreignkey')
    op.drop_index(op.f('ix_car_entries_imported_day_id'), table_name='car_entries')
    op.drop_column('car_entries', 'imported_day_id')
    op.drop_index(op.f('ix_imported_days_date'), table_name='imported_days')
    op.drop_table('imported_days')
    op.drop_index(op.f('ix_import_batches_file_hash'), table_name='import_batches')
    op.drop_table('import_batches')
    # ### end Alembic commands ###
