"""add day_closings table

Revision ID: 239701e4909d
Revises: 2a646712c44f
Create Date: 2026-09-13 19:11:35.334666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239701e4909d'
down_revision: Union[str, None] = '2a646712c44f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_closings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('opening_cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cash_collected', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cash_expenses', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cash_to_partner', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('denominations', sa.JSON(), nullable=False),
    sa.Column('opening_bank', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('closing_bank', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_day_closings_date'), 'day_closings', ['date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_day_closings_date'), table_name='day_closings')
    op.drop_table('day_closings')
    # ### end Alembic commands ###
