"""invoice line items

Revision ID: 2a646712c44f
Revises: 64be9dd39dca
Create Date: 2026-08-28 00:39:43.644046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a646712c44f'
down_revision: Union[str, None] = '64be9dd39dca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute('DELETE FROM invoices')
    op.add_column('invoices', sa.Column('customer_name', sa.String(length=120), nullable=False))
    op.drop_column('invoices', 'reg_no')
    op.drop_column('invoices', 'car_model')
    op.drop_column('invoices', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('car_model', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('reg_no', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_column('invoices', 'customer_name')
    op.drop_table('invoice_items')
    # ### end Alembic commands ###
