"""add discount to puc_entries

Revision ID: 2beb5dc782ea
Revises: 36dd8e988a2c
Create Date: 2026-08-27 22:54:45.820790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2beb5dc782ea'
down_revision: Union[str, None] = '36dd8e988a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puc_entries', sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puc_entries', 'discount')
    # ### end Alembic commands ###
