"""add invoice quantity and amount received

Revision ID: c15d8b18854c
Revises: 112374d61292
Create Date: 2026-09-13 19:52:00.682191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c15d8b18854c'
down_revision: Union[str, None] = '112374d61292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Existing rows need a value, so add the columns with a server default and
    # then drop the default — new rows get theirs from the model.
    op.add_column(
        'invoice_items',
        sa.Column('quantity', sa.Integer(), nullable=False, server_default='1'),
    )
    op.add_column(
        'invoices',
        sa.Column(
            'amount_received',
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            server_default='0',
        ),
    )
    op.alter_column('invoice_items', 'quantity', server_default=None)
    op.alter_column('invoices', 'amount_received', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'amount_received')
    op.drop_column('invoice_items', 'quantity')
    # ### end Alembic commands ###
